# Generated by Django 5.1.6 on 2025-04-10 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imdb_api", "0002_alter_watchlist_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="platform",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watch_list",
                to="imdb_api.streamplateform",
            ),
        ),
    ]
