# Generated by Django 5.1.6 on 2025-04-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imdb_api", "0005_review_review_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="avg_rating",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="number_rating",
            field=models.IntegerField(default=0),
        ),
    ]
